---
title: "Sierpinski3d. ptSNE"
author: |-
  J.Garriga; F.Bartumeus\
  ICREA Movement Ecology Laboratory (CEAB-CSIC)\
  jgarriga@ceab.csic.es
date: "bigMap_4.5.0, `r format(Sys.Date(), '%b %Y')`"
output: html_document
---

```{r, echo = FALSE}
library(knitr)
library(kableExtra)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, }
library(bigMap)
```

### Load data

```{r, }
D <- as.matrix(read.csv('../sierpinski3d.mtx', sep = '', header = F))
```

### Initialize (compute bandwidths)

```{r, eval = F}
# set range of perplexities
ppxs <- round(nrow(D) *c(.01, .05, .1, .2, .3, .4, .5, .6, .7, .8, .9, .95, .99), 0)
# compute betas
G <- bdm.init(D, dSet.name = 's3d', is.distance = T, ppx = ppxs, threads = 4)
```

### Run ptSNE

```{r, eval = F}
g.list <- bdm.ptsne(D, G, lRate = NULL, theta = .0, qlty = T, threads = 1, layers = 1)
# save
save(g.list, file = './glist.RData')
```

```{r, echo = F}
load('./glist.RData')
```

### Embedding cost/size function

```{r, out.width = '33%', fig.show = 'hold'}
nulL <- lapply(g.list, function(g) bdm.cost(g))
```

### Output

```{r, out.width = '33%', fig.show = 'hold'}
# source graph plot
source('../graphs.R')
# load edge matrix
E <- as.matrix(read.csv('../sierpinski3d.edg', sep = '', header = F))
# plot
nulL <- lapply(g.list, function(g) graph.plot(g, E))
```

### hl-Correlation

```{r, eval = F}
g.list <- lapply(g.list, function(g) bdm.hlCorr(D, g, zSampleSize = 1000, threads = 4))
save(g.list, file = './glist.RData')
```

```{r, }
hlTable <- t(sapply(g.list, function(g) summary(g$hlC)))
rownames(hlTable) <- sapply(g.list, function(g) g$ppx$ppx)
knitr::kable(hlTable, caption = 'hl-Correlation') %>%
  kable_styling(full_width = F)
```

### Kary-neighborhood preservation

```{r, eval = F}
g.list <- lapply(g.list, function(g) bdm.knp(D, g, k.max = NULL, sampling = 0.9, threads = 4))
save(g.list, file = './glist.RData')
```

```{r, }
bdm.knp.plot(g.list, ppxfrmt = 0)
```

### Running Times

```{r, }
rTimes <- sapply(g.list, function(g) c(g$ppx$t[3], g$t$epoch, g$t$ptsne[3], (g$ppx$t[3] +g$t$ptsne[3])))
rTimes <- round(rTimes, 1)
colnames(rTimes) <- sapply(g.list, function(g) g$ppx$ppx)
rownames(rTimes) <- c('betas', 'epoch', 'pt-SNE', 'total')
knitr::kable(rTimes, caption = 'Computation times (s)') %>%
  kable_styling(full_width = F)
```

*Run on: Intel(R) Xeon(R) CPU E31225 @ 3.10GHz, 4 cores, 16GB RAM.*
