---
title: "Tasic_2018. pt-SNE"
author: |-
  J.Garriga; F.Bartumeus\
  ICREA Movement Ecology Laboratory (CEAB-CSIC)\
  jgarriga@ceab.csic.es
date: "Version 4.5.0, `r format(Sys.Date(), '%b %Y')`"
output: html_document
---

```{r, echo = FALSE}
library(knitr)
library(kableExtra)
```
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, }
library(bigMap)
```

### Load data

```{r, }
X50 <- as.matrix(read.csv('./tscX50.csv', header = FALSE))
Lbls <- as.matrix(read.csv('./tscLbls.csv', header = FALSE))
```

### Initialize

```{r, }
ppx.list <- round(nrow(X50) * c(.001, .005, .01, .05, .10, .20), 0)
m <- bdm.init(X50, dSet.name = 'Tasic50', ppx = ppx.list, threads = 4, labels = Lbls)
```

### ptSNE

```{r, }
load('./tsc50_tht00.RData')
```

```{r, }
str(m.list[[1]]$ptsne[1:6])
```

```{r, }
sapply(m.list, function(m) m$Xbeta$ppx)
```

### Output

```{r, out.width = '33%', fig.show = 'hold'}
nulL <- lapply(m.list, function(m) bdm.cost(m))
```

```{r, echo = FALSE, out.width = '33%', fig.show = 'hold'}
load('../../tsc50.RData')
nulL <- lapply(m.list, function(m) {
  m$lbls <- tsc50$lbls
  bdm.ptsne.plot(m, ptsne.cex = 0.5, class.pltt = tsc50$pltt)
})
```

### Beta quantile maps

```{r, out.width = '33%', fig.show = 'hold'}
nulL <- lapply(m.list, function(m) bdm.qMap.beta(m))
```

### hl-Correlation

```{r, }
hlTable <- t(sapply(m.list, function(m) summary(m$hlC)))
rownames(hlTable) <- sapply(m.list, function(m) m$Xbeta$ppx)
knitr::kable(hlTable, caption = 'hl-Correlation') %>%
  kable_styling(full_width = F)
```

### Kary-neighborhood preservation

```{r, }
bdm.qlty.plot(m.list, qm = 'kn', ppxfrmt = 4)
```

### Running Times

```{r, }
rTimes <- round(mlist.rTimes(m.list) /60, 2)
knitr::kable(rTimes, caption = 'Computation times (min)') %>%
  kable_styling(full_width = F)
```

*Run on: Intel(R) Xeon(R) CPU E5-2650 v3 2.30GHz, 32Mb cache, 41 cores, 4GB/core RAM.*
