---
title: "Primes1M. FIt-SNE"
author: |-
  J.Garriga; F.Bartumeus\
  ICREA Movement Ecology Laboratory (CEAB-CSIC)\
  jgarriga@ceab.csic.es
date: "`r format(Sys.Date(), '%b %Y')`"
output: html_document
---

```{r, echo = FALSE}
library(knitr)
library(kableExtra)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, }
library(bigMap)
# load aux. stuff 
source('../primes.R')
```

### Load data

```{r, }
load('../P1M.RData')
```

### Run FIt-SNE

Use the script below to run FIt-SNE on a HPC platform with 20 cores and 8GB/core,

```
# ./FItSNE/P1M_start.R: 
# Run FIt-SNE on Primes1M

import numpy as np
import scipy.sparse
import sympy
import json
import time

from openTSNE import TSNEEmbedding
from openTSNE.affinity import PerplexityBasedNN
from openTSNE import initialization

# silence warnings
import warnings
warnings.filterwarnings("ignore")

# +++ data
max_ints = 1000000
primes = list(sympy.primerange(2, max_ints +1))
prime_to_column = {p:i for i, p in enumerate(primes)}

X_rows = [[0]]
X_data = [[0]]
for n in range(2, max_ints +1):
    f = sympy.factorint(n)
    X_rows.append([prime_to_column[p] for p in f.keys()])
    X_data.append([v for v in f.values()])

X = scipy.sparse.X_matrix((len(X_rows), len(primes)), dtype=np.float32)
X.rows = np.array(X_rows)
X.data = np.array(X_data)

output = {}
# +++ perplexities
for ppx in [50, 100, 200, 300, 400]:

  # +++ affinities
  strt = time.time()
  X_affi = PerplexityBasedNN(X, perplexity = ppx, metric = "euclidean", n_jobs = -1, random_state = 55, verbose = True)
  tX2P = time.time() - strt
  
  # +++ FIt-SNE
  strt = time.time()
  Y_init = initialization.random(max_ints, random_state = 55, verbose = T)
  fi_Emb = TSNEEmbedding(Y_init, X_affi, negative_gradient_method = "fft", n_jobs = -1, verbose = True)
  fi_Em1 = fi_Emb.optimize(n_iter = 250, exaggeration = 12, momentum = 0.5)
  fi_Em2 = fi_Em1.optimize(n_iter = 750, momentum = 0.8)
  t = time.time() -strt
  
  output[str(ppx)] = {'Y': fi_Em2.tolist(), 'ppx': ppx, 'tX2P': tX2P, 't': t}
  # +++ save up to here
  with open('./FItSNE/P1M_fitsne.json', 'w') as g:
          json.dump(fi_output, g)

```

Submit:

```
$ qsub -pe make 20 -l h_vmem=8G pySckt ~/FItSNE/P1M_start.R
```
### Convert from json to RData

```{r, eval = F}
json.list <- rjson::fromJSON(file = './FItSNE/P1M_fitsne.json')
m.list <- lapply(json.list, function(j){
  m <- list(dSet = 'P1M', is.distance = F, is.sparse = T, normalize = T)
  m$ppx <- list(ppx = j$ppx)
  m$ptsne <- list(threads = 20, GB = 160, Y = matrix(unlist(j$Y), ncol = 2, byrow = T))
  m$t <- list(affinities = j$tX2P, fitsne = j$t)
  m
})
save(m.list, file = './P1M_fitsne.RData')
```

```{r, }
# load m.list 
load('./P1M_fitsne.RData')
```

### Output

```{r, out.width = '50%', fig.show = 'hold'}
nulL <- lapply(m.list, function(m) primes.plot(P1M, m))
```

### hl-Correlation

```{r, }
hlTable <- sapply(m.list, function(m) summary(m$hlC)[4])
hlTable <- matrix(round(hlTable, 4), nrow = 1)
colnames(hlTable) <- sapply(m.list, function(m) m$ppx$ppx)
rownames(hlTable) <- c('<hlC>')
knitr::kable(hlTable, caption = 'hl-Correlation') %>%
  kable_styling(full_width = F)
```

### k-ary neighborhood preservation

```{r, }
bdm.knp.plot(m.list, ppxfrmt = 0)
```

### Running Times

```{r, }
rTimes <- sapply(m.list, function(m) c(m$t$affinities, m$t$fitsne))
rTimes <- round(rbind(rTimes, apply(rTimes, 2, sum)) /60, 2)
colnames(rTimes) <- sapply(m.list, function(m) m$ppx$ppx)
rownames(rTimes) <- c('affinities', 'FIt-SNE', 'total')
knitr::kable(rTimes, caption = 'Computation times (min)') %>%
  kable_styling(full_width = F)
```

*Run on: Intel(R) Xeon(R) CPU E5-2650 v3 2.30GHz, 32Mb cache, 20 cores, 8GB/core RAM.*

