# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sortZidx <- function(z, zIdx) {
    .Call(`_bigMap_sortZidx`, z, zIdx)
}

thread_affMtx <- function(z_ini, z_end, sexpX, isDistance, isSparse, sexpB, sexpP, sexpW) {
    .Call(`_bigMap_thread_affMtx`, z_ini, z_end, sexpX, isDistance, isSparse, sexpB, sexpP, sexpW)
}

thread_repF <- function(z_ini, z_end, sexpY, theta, sexpR) {
    .Call(`_bigMap_thread_repF`, z_ini, z_end, sexpY, theta, sexpR)
}

thread_mIter <- function(z_ini, z_end, sexpP, sexpW, sexpY, sumP, sumQ, sexpR, sexpU, sexpG, eta, alpha, gain) {
    .Call(`_bigMap_thread_mIter`, z_ini, z_end, sexpP, sexpW, sexpY, sumP, sumQ, sexpR, sexpU, sexpG, eta, alpha, gain)
}

z_kNP <- function(thread_rank, threads, sexpX, sexpY, is_distance, is_sparse, K, sampling) {
    .Call(`_bigMap_z_kNP`, thread_rank, threads, sexpX, sexpY, is_distance, is_sparse, K, sampling)
}

z_hlCorr <- function(sexpX, sexpY, zSampleSize, is_distance, is_sparse) {
    .Call(`_bigMap_z_hlCorr`, sexpX, sexpY, zSampleSize, is_distance, is_sparse)
}

grid_init <- function(X, Y) {
    .Call(`_bigMap_grid_init`, X, Y)
}

grid_p2cell <- function(x, y, grid) {
    .Call(`_bigMap_grid_p2cell`, x, y, grid)
}

grid_D2cell <- function(D, grid) {
    .Call(`_bigMap_grid_D2cell`, D, grid)
}

grid_n2cell <- function(n, grid) {
    .Call(`_bigMap_grid_n2cell`, n, grid)
}

grid_N2cell <- function(grid) {
    .Call(`_bigMap_grid_N2cell`, grid)
}

grid_M2cell <- function(M, grid) {
    .Call(`_bigMap_grid_M2cell`, M, grid)
}

grid_bound <- function(n, grid) {
    .Call(`_bigMap_grid_bound`, n, grid)
}

grid_cross <- function(n, grid) {
    .Call(`_bigMap_grid_cross`, n, grid)
}

grid_peaks <- function(Z, grid) {
    .Call(`_bigMap_grid_peaks`, Z, grid)
}

wtt_cpp <- function(X, Y, Z) {
    .Call(`_bigMap_wtt_cpp`, X, Y, Z)
}

centerScale <- function(sexpX, is_distance, is_sparse) {
    invisible(.Call(`_bigMap_centerScale`, sexpX, is_distance, is_sparse))
}

zBeta <- function(thread_rank, threads, sexpX, is_distance, is_sparse, ppx, xppx) {
    .Call(`_bigMap_zBeta`, thread_rank, threads, sexpX, is_distance, is_sparse, ppx, xppx)
}

zBeta_lambertWm1 <- function(thread_rank, threads, sexpX, is_distance, is_sparse, ppx, xppx) {
    .Call(`_bigMap_zBeta_lambertWm1`, thread_rank, threads, sexpX, is_distance, is_sparse, ppx, xppx)
}

sckt_zTSNE <- function(thread_rank, threads, layers, sexpX, sexpB, sexpY, sexpI, iters, nnSize, theta, lRate, alpha, gain, isDistance, isSparse) {
    .Call(`_bigMap_sckt_zTSNE`, thread_rank, threads, layers, sexpX, sexpB, sexpY, sexpI, iters, nnSize, theta, lRate, alpha, gain, isDistance, isSparse)
}

zChnks <- function(Z_list, Y, I, brks_list) {
    invisible(.Call(`_bigMap_zChnks`, Z_list, Y, I, brks_list))
}

updateY <- function(Y, I, zMap_list, brks_list) {
    invisible(.Call(`_bigMap_updateY`, Y, I, zMap_list, brks_list))
}

mpi_zTSNE <- function(sexpX, sexpB, Y, indexes, iters, nnSize, theta, lRate, alpha, gain, isDistance, isSparse) {
    .Call(`_bigMap_mpi_zTSNE`, sexpX, sexpB, Y, indexes, iters, nnSize, theta, lRate, alpha, gain, isDistance, isSparse)
}

nnSS_chk <- function(sexpX, sexpB, indexes, isDistance, isSparse, nnSize) {
    .Call(`_bigMap_nnSS_chk`, sexpX, sexpB, indexes, isDistance, isSparse, nnSize)
}

